### ISSUE TITLE
Sierra 10.12.2 working?

### ISSUE THREAD

**Issue by tommymachine** [PMheart/macOS-SIP-Opengated#2]
After running the script and receiving message "All done! Now SIP got open-gated", then running " sudo csrutil disable " I am still receiving message "this tool needs to be executed from the Recovery OS."

Do you have solution working on sierra 10.12.2?
Thanks

**Comment by PMheart** [comment]
This is compatible with 10.12.2. Could you upload all logs printed by openGate.sh? That may help more. Thanks.
Ah also. You need to restart. Have you restarted yet? To restart may resolve this issue.

**Comment by tommymachine** [comment]
Restarting would probably fix. I am attempting to recover data entered into a form on safari by attaching gdb to the process for that tab and dumping, and since SIP is blocking " gdb attach PID ", I'm trying to disable SIP without restarting (restarting would kill the process, erasing the data)... not sure if there is any workaround.

**Comment by PMheart** [comment]
That could be impossible...
Let's have a look on how SIP works:
When your case is starting up, boot.efi gather 'csr-active-config' (This is related to the configuration of SIP.) and then initialize kernel/SIP according to 'csr-active-config'.
Note: 'csr-active-config' is a NVRAM key. And thus this means we have to restart to make all changes on this take effect.
Sorry... I don't get any bugs on SIP now... All bugs I knew previously (About El Capitan is in Beta Program) have been fixed.
I think no workaround here. The only thing you should do that is to reboot. Sadly.

**Comment by tommymachine** [comment]
I think you're right. In any case, nice script.
